export const tagsOptions = [
	{ name: 'libft' },
	{ name: 'born2beroot' },
	{ name: 'minishell' },
	{ name: 'ft_server' },
	{ name: 'netwhat' },
	{ name: 'ft_printf' },
	{ name: 'cub3d' },
	{ name: 'get_next_line' },
	{ name: 'ft_services' },
	{ name: 'ft_containers' },
	{ name: 'ft_transcendence' },
	{ name: 'ft_irc' },
	{ name: 'ft_traceroute' },
	{ name: 'ft_hangouts' },
	{ name: 'docker' },
	{ name: '42' },
	{ name: 'C' },
	{ name: 'C++' },
	{ name: 'C#' },
	{ name: 'Java' },
	{ name: 'Python' },
	{ name: 'PHP' },
	{ name: 'HTML' },
	{ name: 'CSS' },
	{ name: 'Javascript' },
	{ name: 'React' },
	{ name: 'Vue' },
	{ name: 'Angular' },
	{ name: 'Node' },
	{ name: 'Express' },
	{ name: 'Django' },
	{ name: 'Flask' },
	{ name: 'Laravel' },
	{ name: 'Symfony' },
	{ name: 'Ruby' },
	{ name: 'Rails' },
	{ name: 'Go' },
	{ name: 'Rust' },
	{ name: 'Swift' },
	{ name: 'Kotlin' },
	{ name: 'Android' },
	{ name: 'IOS' },
	{ name: 'Unity' },
	{ name: 'Unreal' },
	{ name: 'Blender' },
	{ name: 'Maya' },
	{ name: '3DS Max' },
	{ name: 'Photoshop' },
	{ name: 'Illustrator' },
	{ name: 'Premiere' },
	{ name: 'After Effects' },
	{ name: 'Figma' },
	{ name: 'Sketch' },
	{ name: 'Invision' },
	{ name: 'Zeplin' },
	{ name: 'Framer' },
	{ name: 'Adobe XD' },
	{ name: 'InDesign' },
	{ name: 'Lightroom' },
	{ name: 'AutoCAD' },
	{ name: 'SolidWorks' },
	{ name: 'SketchUp' },


]